_wandb:
    value:
        cli_version: 0.25.0
        e:
            6re561cwvvfoqe8nzr4k0c28ul8wr0p6:
                args:
                    - -d
                    - mnist
                    - -l
                    - cross_entropy
                    - -o
                    - RMSprop
                    - -lr
                    - "0.01"
                    - -nhl
                    - "1"
                    - -sz
                    - "4"
                    - -a
                    - sigmoid
                    - -w_i
                    - random
                    - -e
                    - "5"
                    - -b
                    - "64"
                    - -msp
                    - best_model.npy
                cpu_count: 14
                cpu_count_logical: 20
                disk:
                    /:
                        total: "8211378176"
                        used: "135168"
                email: cs22b051@smail.iitm.ac.in
                executable: /home/anshmeshram/Desktop/main folder IIT MADRAS/semester 8 year 4/DL/Assignment_1/venv/bin/python
                host: fedora
                memory:
                    total: "16422760448"
                os: Linux-6.18.13-200.fc43.x86_64-x86_64-with-glibc2.42
                program: -m src.inference
                python: CPython 3.13.11
                root: /home/anshmeshram/Desktop/main folder IIT MADRAS/semester 8 year 4/DL/Assignment_1/da6401_assignment_1-main
                startedAt: "2026-03-05T12:08:40.625848Z"
                writerId: 6re561cwvvfoqe8nzr4k0c28ul8wr0p6
        m: []
        python_version: 3.13.11
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 16
            "4": 3.13.11
            "5": 0.25.0
            "12": 0.25.0
            "13": linux-x86_64
activation:
    value: sigmoid
batch:
    value: "64"
dataset:
    value: mnist
epochs:
    value: "5"
hidden_size:
    value: "4"
learning_rate:
    value: "0.01"
loss:
    value: cross_entropy
model_path:
    value: best_model.npy
num_layers:
    value: "1"
optimizer:
    value: RMSprop
wandb_project:
    value: null
weight_decay:
    value: null
weight_init:
    value: random
