_wandb:
    value:
        cli_version: 0.25.0
        e:
            kuyogwthcuzkztoofi8yoc17cywbg42p:
                codePath: 2_2_dup.py
                codePathLocal: 2_2_dup.py
                email: cs22b051@smail.iitm.ac.in
                executable: /home/anshmeshram/Desktop/main folder IIT MADRAS/semester 8 year 4/DL/Assignment_1/venv/bin/python
                host: fedora
                os: Linux-6.18.12-200.fc43.x86_64-x86_64-with-glibc2.42
                program: /home/anshmeshram/Desktop/main folder IIT MADRAS/semester 8 year 4/DL/Assignment_1/da6401_assignment_1-main/2_2_dup.py
                python: CPython 3.13.11
                root: /home/anshmeshram/Desktop/main folder IIT MADRAS/semester 8 year 4/DL/Assignment_1/da6401_assignment_1-main
                startedAt: "2026-02-26T23:08:05.854170Z"
                writerId: kuyogwthcuzkztoofi8yoc17cywbg42p
        m: []
        python_version: 3.13.11
        t:
            "3":
                - 2
                - 14
            "4": 3.13.11
            "5": 0.25.0
            "12": 0.25.0
            "13": linux-x86_64
activation:
    value: tanh
batch:
    value: 128
dataset:
    value: mnist
epochs:
    value: 40
hidden_size:
    value: 32
learning_rate:
    value: 0.001886347540894658
loss:
    value: mse
num_layers:
    value: 1
optimizer:
    value: momentum
weight_init:
    value: xavier
