_wandb:
    value:
        cli_version: 0.25.0
        e:
            bl0emve8zwnctx0l9nihs9zrv9u4yuh9:
                args:
                    - -d
                    - mnist
                    - -e
                    - "40"
                    - -b
                    - "128"
                    - -l
                    - cross_entropy
                    - -o
                    - nadam
                    - -lr
                    - "0.016853722068101214"
                    - -nhl
                    - "2"
                    - -sz
                    - "16"
                    - -a
                    - relu
                    - -w_i
                    - xavier
                    - -wp
                    - DA_assign_1
                    - -msp
                    - model_id1g9hz6.txt
                cpu_count: 14
                cpu_count_logical: 20
                disk:
                    /:
                        total: "8211382272"
                        used: "135168"
                email: cs22b051@smail.iitm.ac.in
                executable: /home/anshmeshram/Desktop/main folder IIT MADRAS/semester 8 year 4/DL/Assignment_1/venv/bin/python
                host: fedora
                memory:
                    total: "16422768640"
                os: Linux-6.18.12-200.fc43.x86_64-x86_64-with-glibc2.42
                program: -m src.train
                python: CPython 3.13.11
                root: /home/anshmeshram/Desktop/main folder IIT MADRAS/semester 8 year 4/DL/Assignment_1/da6401_assignment_1-main
                startedAt: "2026-02-26T23:38:30.284511Z"
                writerId: bl0emve8zwnctx0l9nihs9zrv9u4yuh9
        m: []
        python_version: 3.13.11
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 2
                - 14
                - 16
            "4": 3.13.11
            "5": 0.25.0
            "12": 0.25.0
            "13": linux-x86_64
activation:
    value: relu
batch:
    value: 128
dataset:
    value: mnist
epochs:
    value: 40
hidden_size:
    value: 16
learning_rate:
    value: 0.016853722068101214
loss:
    value: cross_entropy
model_save_path:
    value: model_id1g9hz6.txt
num_layers:
    value: 2
optimizer:
    value: nadam
wandb_project:
    value: DA_assign_1
weight_decay:
    value: null
weight_init:
    value: xavier
