_wandb:
    value:
        cli_version: 0.25.0
        e:
            je1qlkrb830i94m0nym8voc3nyhtrlav:
                codePath: 2_2_dup.py
                codePathLocal: 2_2_dup.py
                email: cs22b051@smail.iitm.ac.in
                executable: /home/anshmeshram/Desktop/main folder IIT MADRAS/semester 8 year 4/DL/Assignment_1/venv/bin/python
                host: fedora
                os: Linux-6.18.12-200.fc43.x86_64-x86_64-with-glibc2.42
                program: /home/anshmeshram/Desktop/main folder IIT MADRAS/semester 8 year 4/DL/Assignment_1/da6401_assignment_1-main/2_2_dup.py
                python: CPython 3.13.11
                root: /home/anshmeshram/Desktop/main folder IIT MADRAS/semester 8 year 4/DL/Assignment_1/da6401_assignment_1-main
                startedAt: "2026-02-26T22:18:37.835283Z"
                writerId: je1qlkrb830i94m0nym8voc3nyhtrlav
        m: []
        python_version: 3.13.11
        t:
            "3":
                - 2
                - 14
            "4": 3.13.11
            "5": 0.25.0
            "12": 0.25.0
            "13": linux-x86_64
activation:
    value: relu
batch:
    value: 64
dataset:
    value: mnist
epochs:
    value: 20
hidden_size:
    value: 16
learning_rate:
    value: 0.0020686726990987595
loss:
    value: cross_entropy
num_layers:
    value: 3
optimizer:
    value: nag
weight_init:
    value: xavier
