wandb_version: 1

activation:
  value: relu
batch:
  value: 64
dataset:
  value: mnist
epochs:
  value: 40
hidden_size:
  value: 64
learning_rate:
  value: 0.0025662417040582352
loss:
  value: cross_entropy
num_layers:
  value: 1
optimizer:
  value: RMSprop
weight_init:
  value: random
