wandb_version: 1

activation:
  value: tanh
batch:
  value: 32
dataset:
  value: mnist
epochs:
  value: 20
hidden_size:
  value: 16
learning_rate:
  value: 0.006109815274175804
loss:
  value: mse
num_layers:
  value: 1
optimizer:
  value: momentum
weight_init:
  value: random
