wandb_version: 1

activation:
  value: sigmoid
batch:
  value: 64
dataset:
  value: mnist
epochs:
  value: 5
hidden_size:
  value: 32
learning_rate:
  value: 0.002312942326465404
loss:
  value: mse
num_layers:
  value: 1
optimizer:
  value: momentum
weight_init:
  value: xavier
