wandb_version: 1

activation:
  value: sigmoid
batch:
  value: 64
dataset:
  value: mnist
epochs:
  value: 10
hidden_size:
  value: 32
learning_rate:
  value: 0.0632703111929709
loss:
  value: mse
num_layers:
  value: 3
optimizer:
  value: adam
weight_init:
  value: random
