wandb_version: 1

activation:
  value: sigmoid
batch:
  value: 128
dataset:
  value: mnist
epochs:
  value: 40
hidden_size:
  value: 64
learning_rate:
  value: 0.0006140530703073478
loss:
  value: mse
num_layers:
  value: 1
optimizer:
  value: RMSprop
weight_init:
  value: random
