wandb_version: 1

activation:
  value: tanh
batch:
  value: 128
dataset:
  value: mnist
epochs:
  value: 10
hidden_size:
  value: 64
learning_rate:
  value: 0.0969841282474088
loss:
  value: mse
num_layers:
  value: 1
optimizer:
  value: adam
weight_init:
  value: random
