wandb_version: 1

activation:
  value: sigmoid
batch:
  value: 64
dataset:
  value: mnist
epochs:
  value: 5
hidden_size:
  value: 64
learning_rate:
  value: 0.001903179034263026
loss:
  value: mse
num_layers:
  value: 2
optimizer:
  value: nadam
weight_init:
  value: xavier
