wandb_version: 1

activation:
  value: tanh
batch:
  value: 64
dataset:
  value: mnist
epochs:
  value: 40
hidden_size:
  value: 16
learning_rate:
  value: 0.0002566066009904746
loss:
  value: cross_entropy
num_layers:
  value: 1
optimizer:
  value: RMSprop
weight_init:
  value: random
