wandb_version: 1

activation:
  value: tanh
batch:
  value: 32
dataset:
  value: mnist
epochs:
  value: 40
hidden_size:
  value: 32
learning_rate:
  value: 0.057080999720038904
loss:
  value: cross_entropy
num_layers:
  value: 1
optimizer:
  value: RMSprop
weight_init:
  value: random
