wandb_version: 1

activation:
  value: sigmoid
batch:
  value: 128
dataset:
  value: mnist
epochs:
  value: 20
hidden_size:
  value: 64
learning_rate:
  value: 0.03297458699122629
loss:
  value: mse
num_layers:
  value: 3
optimizer:
  value: adam
weight_init:
  value: xavier
