wandb_version: 1

activation:
  value: relu
batch:
  value: 128
dataset:
  value: mnist
epochs:
  value: 5
hidden_size:
  value: 32
learning_rate:
  value: 0.027471949018473905
loss:
  value: cross_entropy
num_layers:
  value: 3
optimizer:
  value: momentum
weight_init:
  value: xavier
