wandb_version: 1

activation:
  value: relu
batch:
  value: 32
dataset:
  value: mnist
epochs:
  value: 40
hidden_size:
  value: 16
learning_rate:
  value: 0.0002044427906980757
loss:
  value: mse
num_layers:
  value: 3
optimizer:
  value: nadam
weight_init:
  value: random
