wandb_version: 1

activation:
  value: tanh
batch:
  value: 64
dataset:
  value: mnist
epochs:
  value: 10
hidden_size:
  value: 32
learning_rate:
  value: 0.0003106402590841206
loss:
  value: mse
num_layers:
  value: 2
optimizer:
  value: momentum
weight_init:
  value: xavier
