wandb_version: 1

activation:
  value: sigmoid
batch:
  value: 64
dataset:
  value: mnist
epochs:
  value: 40
hidden_size:
  value: 16
learning_rate:
  value: 0.0009850699682799014
loss:
  value: cross_entropy
num_layers:
  value: 2
optimizer:
  value: sgd
weight_init:
  value: random
