wandb_version: 1

activation:
  value: tanh
batch:
  value: 128
dataset:
  value: mnist
epochs:
  value: 5
hidden_size:
  value: 16
learning_rate:
  value: 0.002808532385406324
loss:
  value: cross_entropy
num_layers:
  value: 2
optimizer:
  value: RMSprop
weight_init:
  value: xavier
