wandb_version: 1

activation:
  value: relu
batch:
  value: 64
dataset:
  value: mnist
epochs:
  value: 40
hidden_size:
  value: 32
learning_rate:
  value: 0.014603707648894649
loss:
  value: cross_entropy
num_layers:
  value: 1
optimizer:
  value: adam
weight_init:
  value: random
