wandb_version: 1

activation:
  value: sigmoid
batch:
  value: 64
dataset:
  value: mnist
epochs:
  value: 10
hidden_size:
  value: 64
learning_rate:
  value: 0.0038637905881839033
loss:
  value: mse
num_layers:
  value: 2
optimizer:
  value: nag
weight_init:
  value: random
