wandb_version: 1

activation:
  value: relu
batch:
  value: 32
dataset:
  value: mnist
epochs:
  value: 40
hidden_size:
  value: 32
learning_rate:
  value: 0.00307793582552178
loss:
  value: mse
num_layers:
  value: 2
optimizer:
  value: nadam
weight_init:
  value: random
