wandb_version: 1

activation:
  value: sigmoid
batch:
  value: 32
dataset:
  value: mnist
epochs:
  value: 5
hidden_size:
  value: 32
learning_rate:
  value: 0.0015472448852864456
loss:
  value: cross_entropy
num_layers:
  value: 2
optimizer:
  value: adam
weight_init:
  value: random
