wandb_version: 1

activation:
  value: sigmoid
batch:
  value: 32
dataset:
  value: mnist
epochs:
  value: 20
hidden_size:
  value: 32
learning_rate:
  value: 0.06816493206311224
loss:
  value: mse
num_layers:
  value: 1
optimizer:
  value: adam
weight_init:
  value: xavier
