wandb_version: 1

activation:
  value: relu
batch:
  value: 64
dataset:
  value: mnist
epochs:
  value: 40
hidden_size:
  value: 64
learning_rate:
  value: 0.0006197830585108027
loss:
  value: cross_entropy
num_layers:
  value: 2
optimizer:
  value: adam
weight_init:
  value: random
