wandb_version: 1

activation:
  value: sigmoid
batch:
  value: 32
dataset:
  value: mnist
epochs:
  value: 40
hidden_size:
  value: 16
learning_rate:
  value: 0.0008506337141521717
loss:
  value: cross_entropy
num_layers:
  value: 3
optimizer:
  value: sgd
weight_init:
  value: random
