wandb_version: 1

activation:
  value: sigmoid
batch:
  value: 128
dataset:
  value: mnist
epochs:
  value: 10
hidden_size:
  value: 16
learning_rate:
  value: 0.03396288969125741
loss:
  value: cross_entropy
num_layers:
  value: 2
optimizer:
  value: adam
weight_init:
  value: xavier
