_wandb:
    value:
        cli_version: 0.25.0
        e:
            ia5m3h6msxtpoud4s2mr4k5b2v0fy4fb:
                codePath: 2_1.py
                codePathLocal: 2_1.py
                email: cs22b051@smail.iitm.ac.in
                executable: /home/anshmeshram/Desktop/main folder IIT MADRAS/semester 8 year 4/DL/Assignment_1/venv/bin/python
                host: fedora
                os: Linux-6.18.13-200.fc43.x86_64-x86_64-with-glibc2.42
                program: /home/anshmeshram/Desktop/main folder IIT MADRAS/semester 8 year 4/DL/Assignment_1/da6401_assignment_1-main/part2/2_1.py
                python: CPython 3.13.11
                root: /home/anshmeshram/Desktop/main folder IIT MADRAS/semester 8 year 4/DL/Assignment_1/da6401_assignment_1-main/part2
                startedAt: "2026-03-02T06:17:04.392904Z"
                writerId: ia5m3h6msxtpoud4s2mr4k5b2v0fy4fb
        m: []
        python_version: 3.13.11
        t:
            "4": 3.13.11
            "5": 0.25.0
            "12": 0.25.0
            "13": linux-x86_64
