wandb_version: 1

activation:
  value: tanh
batch:
  value: 128
dataset:
  value: mnist
epochs:
  value: 10
hidden_size:
  value: 32
learning_rate:
  value: 0.0009509434947186692
loss:
  value: mse
num_layers:
  value: 2
optimizer:
  value: RMSprop
weight_init:
  value: random
