wandb_version: 1

activation:
  value: sigmoid
batch:
  value: 64
dataset:
  value: mnist
epochs:
  value: 10
hidden_size:
  value: 32
learning_rate:
  value: 0.0030302336485518327
loss:
  value: mse
num_layers:
  value: 2
optimizer:
  value: adam
weight_init:
  value: xavier
