wandb_version: 1

activation:
  value: relu
batch:
  value: 128
dataset:
  value: mnist
epochs:
  value: 10
hidden_size:
  value: 64
learning_rate:
  value: 0.0001911336435676237
loss:
  value: mse
num_layers:
  value: 3
optimizer:
  value: adam
weight_init:
  value: random
