_wandb:
    value:
        cli_version: 0.25.0
        e:
            rk7b6379h4nzc46m1ip2svof8dla015k:
                args:
                    - -d
                    - mnist
                    - -e
                    - "40"
                    - -b
                    - "32"
                    - -l
                    - cross_entropy
                    - -o
                    - RMSprop
                    - -lr
                    - "0.057080999720038904"
                    - -nhl
                    - "1"
                    - -sz
                    - "32"
                    - -a
                    - tanh
                    - -w_i
                    - random
                    - -wp
                    - DA_assign_1
                    - -msp
                    - model_cj3xwo3s.txt
                cpu_count: 14
                cpu_count_logical: 20
                disk:
                    /:
                        total: "8211382272"
                        used: "135168"
                email: cs22b051@smail.iitm.ac.in
                executable: /home/anshmeshram/Desktop/main folder IIT MADRAS/semester 8 year 4/DL/Assignment_1/venv/bin/python
                host: fedora
                memory:
                    total: "16422768640"
                os: Linux-6.18.12-200.fc43.x86_64-x86_64-with-glibc2.42
                program: -m src.train
                python: CPython 3.13.11
                root: /home/anshmeshram/Desktop/main folder IIT MADRAS/semester 8 year 4/DL/Assignment_1/da6401_assignment_1-main
                startedAt: "2026-02-26T22:21:08.838329Z"
                writerId: rk7b6379h4nzc46m1ip2svof8dla015k
        m: []
        python_version: 3.13.11
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 2
                - 14
                - 16
            "4": 3.13.11
            "5": 0.25.0
            "12": 0.25.0
            "13": linux-x86_64
activation:
    value: tanh
batch:
    value: 32
dataset:
    value: mnist
epochs:
    value: 40
hidden_size:
    value: 32
learning_rate:
    value: 0.057080999720038904
loss:
    value: cross_entropy
model_save_path:
    value: model_cj3xwo3s.txt
num_layers:
    value: 1
optimizer:
    value: RMSprop
wandb_project:
    value: DA_assign_1
weight_decay:
    value: null
weight_init:
    value: random
