wandb_version: 1

activation:
  value: sigmoid
batch:
  value: 128
dataset:
  value: mnist
epochs:
  value: 5
hidden_size:
  value: 32
learning_rate:
  value: 0.00028674249567386153
loss:
  value: mse
num_layers:
  value: 2
optimizer:
  value: RMSprop
weight_init:
  value: random
