wandb_version: 1

activation:
  value: relu
batch:
  value: 128
dataset:
  value: mnist
epochs:
  value: 5
hidden_size:
  value: 32
learning_rate:
  value: 0.08177393984610874
loss:
  value: cross_entropy
num_layers:
  value: 3
optimizer:
  value: adam
weight_init:
  value: random
