wandb_version: 1

activation:
  value: sigmoid
batch:
  value: 32
dataset:
  value: mnist
epochs:
  value: 10
hidden_size:
  value: 256
learning_rate:
  value: 0.000311929929307101
loss:
  value: cross_entropy
num_layers:
  value: 1
optimizer:
  value: momentum
weight_init:
  value: random
