wandb_version: 1

activation:
  value: relu
batch:
  value: 128
dataset:
  value: mnist
epochs:
  value: 10
hidden_size:
  value: 256
learning_rate:
  value: 0.0005118398944375646
loss:
  value: cross_entropy
num_layers:
  value: 2
optimizer:
  value: momentum
weight_init:
  value: random
