wandb_version: 1

activation:
  value: relu
batch:
  value: 32
dataset:
  value: mnist
epochs:
  value: 5
hidden_size:
  value: 256
learning_rate:
  value: 0.0013072553487818062
loss:
  value: mse
num_layers:
  value: 1
optimizer:
  value: sgd
weight_init:
  value: random
