wandb_version: 1

activation:
  value: relu
batch:
  value: 32
dataset:
  value: mnist
epochs:
  value: 10
hidden_size:
  value: 64
learning_rate:
  value: 0.00013878270435004622
loss:
  value: mse
num_layers:
  value: 2
optimizer:
  value: adam
weight_init:
  value: random
