wandb_version: 1

activation:
  value: sigmoid
batch:
  value: 64
dataset:
  value: mnist
epochs:
  value: 5
hidden_size:
  value: 64
learning_rate:
  value: 0.0004643170317659589
loss:
  value: cross_entropy
num_layers:
  value: 3
optimizer:
  value: RMSprop
weight_init:
  value: xavier
