wandb_version: 1

activation:
  value: sigmoid
batch:
  value: 128
dataset:
  value: mnist
epochs:
  value: 10
hidden_size:
  value: 256
learning_rate:
  value: 0.00022587280347174192
loss:
  value: mse
num_layers:
  value: 2
optimizer:
  value: nadam
weight_init:
  value: random
